### ISSUE TITLE
[ERROR] Wrong API introduced to create a partition in tutorial

### ISSUE THREAD

**Issue by yanliang567** [milvus-io/web-content#613]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Where is the error**
https://milvus.io/api-reference/pymilvus-orm/v2.0.alpha/tutorial.html

**How would you like to improve it**
You can provide a partition name to create a new partition.
collection.partition("new_partition")    // this is wrong 
collection.create_partition("new_partition")   // this is the correct one

**Screenshots**

**Comment by shanghaikid** [comment]
@scsven please look into this issue.
