### ISSUE TITLE
[Suggestion]Two contributing buttons at the top right of doc pages link to milvus repo instead of docs repo

### ISSUE THREAD

**Issue by claireyuw** [milvus-io/web-content#658]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Is there anything that's missing or inappropriate in the docs? Please describe.**
Currently we have "Edit this page", "Discuss it on GitHub", and "Report a bug" at the top right section of each doc page, but the latter two both lead to the milvus repo instead of the milvus-docs repo.

**Describe your suggestion**
1. We need to provide a link to direct our audience to submit a doc issue. 
2. The issue submission window automatically has the relevant page name in the issue title block.
3. The link opens the web page in a new tab.

**Additional reference**
https://www.cockroachlabs.com/docs/cockroachcloud/quickstart.html

**Comment by ThyeeZz** [comment]
https://github.com/milvus-io/milvus.io/pull/666
