### ISSUE TITLE
[ERROR]: Doc error

### ISSUE THREAD

**Issue by JackLCL** [milvus-io/web-content#678]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

link: https://milvus.io/hacktoberfest-2021

![image](https://user-images.githubusercontent.com/53512883/140001927-7c68052f-4d9d-44b8-8ec5-4a90a7a52a62.png)

This word is missing one letter "t".

**Comment by shanghaikid** [comment]
fixed
