### ISSUE TITLE
[ERROR]Tutorial doc error in offical website

### ISSUE THREAD

**Issue by OptimusMsc** [milvus-io/web-content#688]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Where is the error**
What is the URL/path of the document related to this issue?
https://milvus.io/cn/api-reference/pymilvus/v2.0.0rc8/tutorial.html

**How would you like to improve it**
From Chapter **Insert Data** to **Structured Match**, there should be `from pymilvus import Collection` rather than `from pymilvus import collection`.

**Screenshots**
![b5a2910dfdb33e99e7589237996c076](https://user-images.githubusercontent.com/8123507/147563474-5735a7df-1034-4763-8567-e0ef183c1ad3.png)

**Comment by shanghaikid** [comment]
Please see this doc. 
https://milvus.io/api-reference/pymilvus/v2.0.0/tutorial.html
