### ISSUE TITLE
[ERROR] About should be consistent between docs & github repo

### ISSUE THREAD

**Issue by jennyli-z** [milvus-io/web-content#689]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Where is the error**
https://milvus.io/community/making_your_first_contributions.md
**How would you like to improve it**
The information for the `about `part should be the same as the `about` information in the github repo 
**Screenshots**
![image](https://user-images.githubusercontent.com/93511422/147729730-0f5f8468-0ab5-459c-9b55-e301f074638d.png)

**Comment by YiyunNi** [comment]
Fixed with PR #751
