### ISSUE TITLE
[ERROR] The "edit this page" button on community pages leads to 404

### ISSUE THREAD

**Issue by YiyunNi** [milvus-io/web-content#752]
> Note: This repository is ONLY used to solve issues related to DOCS.
> For other issues, please move to [other repositories](https://github.com/milvus-io/).

**Where is the error**
https://milvus.io/community/contributing_to_milvus.md

**How would you like to improve it**
Fix the 404 error

**Screenshots**

<img width="1462" alt="截屏2022-10-27 14 23 14" src="https://user-images.githubusercontent.com/74396087/198207255-e555fa84-fc3a-42ad-92f4-6746a5b5c083.png">

**Comment by ThyeeZz** [comment]
fixed
